[build]
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt"
  publish = "."
  functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9.18" 