[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["tensorflow"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[functions.environment]
  PYTHON_VERSION = "3.9"