services:
  - type: web
    name: hate-speech-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: HF_TOKEN
        sync: false  # This means you'll need to set this value in the Render dashboard
      - key: HF_REPO_ID
        value: "your-repo-id"  # Replace with your actual Hugging Face repo ID 