services:
  - type: web
    name: hate-speech-detection
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: HF_TOKEN
        sync: false
      - key: HF_REPO_ID
        value: "AbdelilahElgallati/Hate-model-detection"
    healthCheckPath: /health
    autoDeploy: true 